-- Cohort Revenue Matrix:
-- Shows the revenue contributed by each customer cohort
-- across each calendar month from December 2010 to December 2011.
-- Each row represents a cohort and each column represents
-- the revenue generated by that cohort in a specific month.
--SELECT * FROM  vw_CohortRevenueMatrix ORDER BY CohortMonth
CREATE VIEW vw_CohortRevenueMatrix AS
--C:\Users\Administrator\AppData\Local\Temp\zn55zpay..sql
SELECT
    CohortMonth,

    SUM(CASE 
        WHEN InvoiceDate >= '2010-12-01'
         AND InvoiceDate < '2011-01-01'
        THEN Revenue ELSE 0 
    END) AS [Dec_2010],

    SUM(CASE 
        WHEN InvoiceDate >= '2011-01-01'
         AND InvoiceDate < '2011-02-01'
        THEN Revenue ELSE 0 
    END) AS [Jan_2011],

    SUM(CASE 
        WHEN InvoiceDate >= '2011-02-01'
         AND InvoiceDate < '2011-03-01'
        THEN Revenue ELSE 0 
    END) AS [Feb_2011],

    SUM(CASE 
        WHEN InvoiceDate >= '2011-03-01'
         AND InvoiceDate < '2011-04-01'
        THEN Revenue ELSE 0 
    END) AS [Mar_2011],

    SUM(CASE 
        WHEN InvoiceDate >= '2011-04-01'
         AND InvoiceDate < '2011-05-01'
        THEN Revenue ELSE 0 
    END) AS [Apr_2011],

    SUM(CASE 
        WHEN InvoiceDate >= '2011-05-01'
         AND InvoiceDate < '2011-06-01'
        THEN Revenue ELSE 0 
    END) AS [May_2011],

    SUM(CASE 
        WHEN InvoiceDate >= '2011-06-01'
         AND InvoiceDate < '2011-07-01'
        THEN Revenue ELSE 0 
    END) AS [Jun_2011],

    SUM(CASE 
        WHEN InvoiceDate >= '2011-07-01'
         AND InvoiceDate < '2011-08-01'
        THEN Revenue ELSE 0 
    END) AS [Jul_2011],

    SUM(CASE 
        WHEN InvoiceDate >= '2011-08-01'
         AND InvoiceDate < '2011-09-01'
        THEN Revenue ELSE 0 
    END) AS [Aug_2011],

    SUM(CASE 
        WHEN InvoiceDate >= '2011-09-01'
         AND InvoiceDate < '2011-10-01'
        THEN Revenue ELSE 0 
    END) AS [Sep_2011],

    SUM(CASE 
        WHEN InvoiceDate >= '2011-10-01'
         AND InvoiceDate < '2011-11-01'
        THEN Revenue ELSE 0 
    END) AS [Oct_2011],

    SUM(CASE 
        WHEN InvoiceDate >= '2011-11-01'
         AND InvoiceDate < '2011-12-01'
        THEN Revenue ELSE 0 
    END) AS [Nov_2011],

    SUM(CASE 
        WHEN InvoiceDate >= '2011-12-01'
         AND InvoiceDate < '2012-01-01'
        THEN Revenue ELSE 0 
    END) AS [Dec_2011]

FROM UKRETAIL

WHERE CustomerID IS NOT NULL

GROUP BY CohortMonth;